# Generated by Django 5.1 on 2024-09-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0006_auction_access_fee"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="auctions",
            field=models.ManyToManyField(to="auction.auction"),
        ),
    ]
