# Generated by Django 5.0.6 on 2024-07-04 19:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.TextField()),
                (
                    "initial_price",
                    models.FloatField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                (
                    "sold_price",
                    models.FloatField(
                        default=True,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Auction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_at", models.DateTimeField(default=None, null=True)),
                ("finished_at", models.DateTimeField(default=None, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_conducted", "Not conducted"),
                            ("active", "Active"),
                            ("finished", "Finished"),
                        ],
                        default="not_conducted",
                        max_length=255,
                    ),
                ),
                (
                    "lot",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="auction.lot"
                    ),
                ),
            ],
        ),
    ]
