# Generated by Django 5.1 on 2024-09-09 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0005_auction_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="access_fee",
            field=models.FloatField(
                default=None,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
        migrations.AddField(
            model_name="auction",
            name="requires_payment",
            field=models.BooleanField(default=False),
        ),
    ]
