# Generated by Django 5.1 on 2024-09-16 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auction", "0005_auction_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="auction",
            name="access_fee",
            field=models.FloatField(
                default=None,
                null=True,
                validators=[django.core.validators.MinValueValidator(0.01)],
            ),
        ),
    ]
