# Generated by Django 5.1 on 2024-09-09 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auction", "0006_auction_access_fee_auction_requires_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuctionPaymentInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price_id", models.CharField(max_length=255)),
                ("product_id", models.CharField(max_length=255)),
                (
                    "auction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auction.auction",
                    ),
                ),
            ],
        ),
    ]
